### ISSUE TITLE
删除会议失败

### ISSUE THREAD

**Issue by KKKZOZ** [KKKZOZ/smart-meeting-transcript-system#14]
![image](https://github.com/user-attachments/assets/d8249f70-a43b-4bc4-ba9b-4d307b7c5857)

**Comment by Toconquer1** [comment]
在所有的模型定义的外键属性中增加DELETE ON CASCADE 实现级联删除

**Comment by KKKZOZ** [comment]
This issue was fixed by commit a315beb804735444c62456046c18fb1c4f1fa3aa
Close #14
