### ISSUE TITLE
bug:关于post请求打印日志的问题

### ISSUE THREAD

**Issue by TwilightMayfly** [KKKZOZ/smart-meeting-transcript-system#5]
在进行post请求的时候，如果请求体内存在不能用utf-8解码的内容，会导致错误，并且无法继续进行该请求。

**Comment by KKKZOZ** [comment]
https://github.com/KKKZOZ/smart-meeting-transcript-system/blob/4745e0d938630586a3601e30c195224c5f769bf0/backend/app/middleware/logging.py#L41-L54
